version:'3'
services:
  postgres:
    image:postgres:13
    container_name:posgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    port:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data
volumes:
  postgres_data: